# Generated by Django 5.1 on 2024-08-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kcal', models.IntegerField()),
                ('diet_category', models.IntegerField(choices=[(1, 'Diet 1'), (2, 'Diet 2'), (3, 'Diet 3'), (4, 'Diet 4'), (5, 'Diet 5'), (6, 'Diet 6'), (7, 'Diet 7'), (8, 'Diet 8'), (9, 'Diet 9'), (10, 'Diet 10'), (11, 'Diet 11'), (12, 'Diet 12'), (13, 'Diet 13'), (14, 'Diet 14'), (15, 'Diet 15')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.category')),
            ],
        ),
    ]
