# Generated by Django 5.1 on 2024-08-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuMealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealtime')),
                ('meals', models.ManyToManyField(to='meals.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='meal_times',
            field=models.ManyToManyField(through='meals.MenuMealTime', to='meals.mealtime'),
        ),
    ]
