# Generated by Django 5.1 on 2024-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_menu_menumealtime_menu_meal_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='menumealtime',
            unique_together={('menu', 'meal_time')},
        ),
    ]
