# Generated by Django 5.1 on 2024-08-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMealSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('seat_number', models.IntegerField()),
                ('date_selected', models.DateField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
                ('menu_mealtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.menumealtime')),
            ],
        ),
    ]
